spring:
  data:
    mongodb:
      authentication-database: admin
      #db.createUser({"user":"superadmin","pwd":"123456","roles":[{"role":"readWrite","db":"soc"}]});
      uri: ${cj.geochat.MONGODB_URL:mongodb://superadmin:123456@geochat-ecs.local:27017/soc}